# å°†proxy-providersé‡Œé¢é“¾æ¥ä¸­çš„â€œè®¢é˜…é“¾æ¥â€æ›¿æ¢å³å¯

mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090

subscribe-url: è®¢é˜…é“¾æ¥
#æ›¿æ¢ä¸Šé¢æ–‡å­—ç”¨äºStashè·å–æœºåœºæµé‡ä¿¡æ¯å¹¶åœ¨ä¸»é¡µæ˜¾ç¤º

proxy-providers:
  All:
    type: http
    url: "https://api.v1.mk/sub?target=clash&url=è®¢é˜…é“¾æ¥&emoji=true&list=true&udp=true"
    # ä»¥ä¸‹æ–¹æ³•ä»»é€‰å…¶ä¸€âš ï¸æœ‰Clashè®¢é˜…ä¼˜å…ˆä½¿ç”¨æ–¹æ³•äºŒâ—ï¸
    # 1.å¯ä»¥ä½¿ç”¨ä»»æ„ç±»å‹çš„é“¾æ¥ä»…æ›¿æ¢ä¸Šé¢æ–‡å­—ï¼Œå¤šä¸ªé“¾æ¥ä½¿ç”¨è‹±æ–‡ç¬¦å·çš„ç«–æ |éš”å¼€ä¸€èµ·å†™ä¸Šå³å¯
    # 2.Sub-Storeä¸Clashç±»å‹è®¢é˜…é“¾æ¥æ›¿æ¢æ‰æ•´ä¸ªå¼•å·""å†…çš„é“¾æ¥
    interval: 86400
    path: ./all.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  Music:
    type: http
    url: "https://api.v1.mk/sub?target=clash&url=https://raw.githubusercontent.com/I-am-R-E/Functional-Store-Hub/Master/NeteaseMusic/AgentNode/QuantumultX.snippet&emoji=true&list=true&udp=true"
    # ä»¥ä¸‹æ–¹æ³•ä»»é€‰å…¶ä¸€âš ï¸æœ‰Clashè®¢é˜…ä¼˜å…ˆä½¿ç”¨æ–¹æ³•äºŒâ—ï¸
    # 1.å¯ä»¥ä½¿ç”¨ä»»æ„ç±»å‹çš„é“¾æ¥ä»…æ›¿æ¢ä¸Šé¢æ–‡å­—ï¼Œå¤šä¸ªé“¾æ¥ä½¿ç”¨è‹±æ–‡ç¬¦å·çš„ç«–æ |éš”å¼€ä¸€èµ·å†™ä¸Šå³å¯
    # 2.Sub-Storeä¸Clashç±»å‹è®¢é˜…é“¾æ¥æ›¿æ¢æ‰æ•´ä¸ªå¼•å·""å†…çš„é“¾æ¥
    interval: 86400
    path: ./Music.yaml
    health-check:
      enable: true
      interval: 600
      url: http://interface3.music.163.com
dns:
  enable: true
  ipv6: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - localhost.ptlogin2.qq.com
    - '+.srv.nintendo.net'
    - '+.stun.playstation.net'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - '+.xboxlive.com'
    - 'msftconnecttest.com'
    - 'xbox.*.microsoft.com'
    - '*.battlenet.com.cn'
    - '*.battlenet.com'
    - '*.blzstatic.cn'
    - '*.battle.net'
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query

proxies:
            
proxy-groups:
  - name: æ‰‹åŠ¨åˆ‡æ¢
    type: select
    icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Universal/Select.png
    use:
      - All
    proxies:
      - è‡ªåŠ¨é€‰æ‹©
      - æ•…éšœè½¬ç§»

  - name: è‡ªåŠ¨é€‰æ‹©
    type: url-test
    icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Universal/Auto_Speed.png
    use: 
       - All
    url: "http://www.gstatic.com/generate_204"
    interval: 300
    
  - name: æ•…éšœè½¬ç§»
    type: fallback
    icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Universal/SSID.png
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    use: 
       - All
       
  - name: å›½å¤–ç½‘ç«™
    type: select
    icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Universal/Streaming.png
    proxies: &G
      - æ‰‹åŠ¨åˆ‡æ¢
      - è‡ªåŠ¨é€‰æ‹©
      - æ•…éšœè½¬ç§»
      - é¦™æ¸¯èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹


  - name: å›½å†…ç½‘ç«™
    type: select
    icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Universal/StreamingSE.png
    proxies: &C
      - DIRECT
      - æ‰‹åŠ¨åˆ‡æ¢
      - è‡ªåŠ¨é€‰æ‹©
      - æ•…éšœè½¬ç§»
      - é¦™æ¸¯èŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹

      
  - name: YouTube
    type: select
    icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Social_Media/YouTube.png
    proxies:
      *G

  - name: TikTok
    type: select
    icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Social_Media/TikTok.png
    proxies:
      *G

  - name: Telegram
    type: select
    icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Social_Media/Telegram.png
    proxies:
      *G

  - name: Twitter
    type: select
    icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Social_Media/Twitter.png
    proxies:
      *C

  - name: Instagram
    type: select
    icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Social_Media/Instagram.png
    proxies:
      *G

  - name: Facebook
    type: select
    icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Social_Media/Facebook.png
    proxies:
      *G

  - name: Notion
    type: select
    icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Social_Media/LiveJournal.png
    proxies:
      *G

  - name: Spotify
    type: select
    icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Social_Media/Spotify.png
    proxies:
      *G

  - name: NetEase Music
    type: select
    icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Universal/NetEase_Music.png
    proxies:
      *G

  - name: BiliBili
    type: select
    icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Universal/BiliBili.png
    proxies:
      *C

  - name: /Apple
    type: select
    icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Social_Media/Apple.png
    proxies:
      *C
      
  - name: Google
    type: select
    icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Google_Suite/Google.png
    proxies:
      *G

  - name: Microsoft
    type: select
    icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Universal/Microsoft.png
    proxies:
      *G

  - name: AdBlock
    type: select
    icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Universal/Reject.png
    proxies:
      - REJECT
      
  - name: æ¼ç½‘ä¹‹é±¼
    type: select
    icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Social_Media/Snapfish.png
    proxies:
      *G

  - name: é¦™æ¸¯èŠ‚ç‚¹
    type: select
    icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Rounded_Rectangle/Hong_Kong.png
    use:
      - All
    filter: (?=.*(æ¸¯|ğŸ‡­ğŸ‡°|HK|(?i)Hong))^((?!(å°|æ—¥|éŸ©|æ–°|ç¾)).)*$
      
  - name: æ—¥æœ¬èŠ‚ç‚¹
    type: select
    icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Rounded_Rectangle/Japan.png
    use:
      - All
    filter: (?=.*(æ—¥|ğŸ‡¯ğŸ‡µ|JP|(?i)Japan))^((?!(æ¸¯|å°|éŸ©|æ–°|ç¾)).)*$

  - name: ç¾å›½èŠ‚ç‚¹
    type: select
    icon: https://raw.githubusercontent.com/Semporia/Hand-Painted-icon/master/Rounded_Rectangle/United_States.png
    use:
      - All
    filter: (?=.*(ç¾|ğŸ‡ºğŸ‡¸|US|(?i)States|American))^((?!(æ¸¯|å°|æ—¥|éŸ©|æ–°)).)*$

rule-providers:

  Unbreak:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Unbreak.yaml"
    path: ./ruleset/Unbreak.yaml
    interval: 86400
    
  AD-Ban:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Coldvvater/Clash/master/RuleSet/AD-Ban.yaml"
    path: ./ruleset/AD-Ban.yaml
    interval: 86400

  Privacy:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/Coldvvater/Clash/master/RuleSet/Privacy.yaml"
    path: ./ruleset/Privacy.yaml
    interval: 86400

  Hijacking:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Guard/Hijacking.yaml"
    path: ./ruleset/Hijacking.yaml
    interval: 86400

  YouTube:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml"
    path: ./ruleset/YouTube.yaml
    interval: 86400

  BiliBili:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.yaml"
    path: ./ruleset/BiliBili.yaml
    interval: 86400

  Notion:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Notion/Notion.yaml"
    path: ./ruleset/Notion.yaml
    interval: 86400
    
  Facebook:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Facebook/Facebook.yaml"
    path: ./ruleset/Facebook.yaml
    interval: 86400

  Instagram:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Instagram/Instagram.yaml"
    path: ./ruleset/Instagram.yaml
    interval: 86400

  Telegram:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml"
    path: ./ruleset/Telegram.yaml
    interval: 86400
    
  TikTok:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TikTok/TikTok.yaml"
    path: ./ruleset/TikTok.yaml
    interval: 86400
    
  Twitter:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Twitter/Twitter.yaml"
    path: ./ruleset/Twitter.yaml
    interval: 86400
    
  Apple:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.yaml"
    path: ./ruleset/Apple.yaml
    interval: 86400

  Microsoft:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml"
    path: ./ruleset/Microsoft.yaml
    interval: 86400

  Google:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.yaml"
    path: ./ruleset/Google.yaml
    interval: 86400

  NetEaseMusic:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/NetEaseMusic/NetEaseMusic.yaml"
    path: ./ruleset/NetEaseMusic.yaml
    interval: 86400

  Spotify:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.yaml"
    path: ./ruleset/Spotify.yaml
    interval: 86400

  China:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/China.yaml"
    path: ./ruleset/China.yaml
    interval: 86400

  Global:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Global.yaml"
    path: ./ruleset/Global.yaml
    interval: 86400

  Lan:
    type: http
    behavior: classical
    url: "https://ghproxy.com/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml"
    path: ./ruleset/lan.yaml
    interval: 86400
    
rules:
  - RULE-SET,Unbreak,DIRECT
  - RULE-SET,AD-Ban,AdBlock
  - RULE-SET,Privacy,AdBlock
  - RULE-SET,Hijacking,AdBlock
  - RULE-SET,YouTube,YouTube
  - RULE-SET,TikTok,TikTok
  - RULE-SET,Telegram,Telegram
  - RULE-SET,Twitter,Twitter
  - RULE-SET,Instagram,Instagram
  - RULE-SET,Facebook,Facebook
  - RULE-SET,Notion,Notion
  - RULE-SET,Spotify,Spotify
  - RULE-SET,BiliBili,BiliBili
  - RULE-SET,NetEaseMusic,NetEase Music
  - RULE-SET,Apple,Apple
  - RULE-SET,Microsoft,Microsoft
  - RULE-SET,Google,Google
  - RULE-SET,Global,å›½å¤–ç½‘ç«™
  - RULE-SET,China,å›½å†…ç½‘ç«™
  - RULE-SET,Lan,DIRECT
  - GEOIP,CN,å›½å†…ç½‘ç«™
  - MATCH,æ¼ç½‘ä¹‹é±¼
